### ISSUE TITLE
EventEmitter memory leak detected

### ISSUE THREAD

**Issue by vertangelx** [scttnlsn/monq#45]
When a job is queued for every doc returned from a `collections.find`, I'm getting the warning message

    (node) warning: possible EventEmitter memory leak detected. 51 open listeners added. Use emitter.setMaxListeners() to increase limit.

Example code:

	collection.find({}, function(err, docs) {

		docs.forEach(function(doc, index) {
			queue.enqueue('myJob'...)
		})

	})

Is there a way to clean up the listeners? How can `emitter.setMaxListeners()` be used to increase the limit?

**Comment by scttnlsn** [comment]
Are you sure the issue is w/ Monq?  Monq does not bind any event listeners (only emits events) so I'm not sure where it would be leaking.  Could the problem be elsewhere in your application code?  `Job` and `Worker` objects are instances of `EventEmitter` so you could call `setMaxListeners()` on those if need be.

Please re-open if you discover this is indeed an issue somewhere in Monq.
